.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. kcoin_qt test_kcoin_qt
clean: FORCE
	$(MAKE) -C .. kcoin_qt_clean test_kcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_kcoin_qt_check
kcoin-qt kcoin-qt.exe: FORCE
	 $(MAKE) -C .. kcoin_qt
