#!/bin/bash

# This is a thin wrapper around kcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using kcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_KCOIND

# Grab the value of $REAL_KCOINCLI which may be kcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_KCOINCLI}" "$@" | sed 's/\r//'
